---
key: YOUR_API_KEY
group: testgroup
mode: csv
options:
  - headers: true
    delim:
    - " "
    - ","
    - "{{%d}}"
    cols: >
      {{ $first }}
      {{ second_col:$second }}
      {{ third_col:$3 }}
      {{ $4 }}
