---
mode: ordered
options:
  - match: >
      Filesystem 
      {{ fs_blocks:%mem }}-blocks
  - header: Filesystem
    rows: 5
    table: >
      {{ disk:$0 }}
      {{ (int) total_size:$1 }}
      {{ (int) used_size:$2 }}
      {{ (int) avail_size:$3 }}
      {{ capacity:$4 }}
      {{ iused:$5 }}
      {{ ifree:$6 }}
      {{ pct_iused:$7 }}
