---
key: YOUR_API_KEY
group: testgroup
mode: batch
options:
  - fail: >
      Processes:
  - match: >
      Processes: 
      {{ proc_total:%d }} total, 
      {{ proc_running:%d }} running, 
      {{ proc_stuck:%d }} stuck, 
      {{ proc_sleeping:%d }} sleeping, 
      {{ num_threads:%d }} threads
  - match: >
      Load Avg: 
      {{ load_1:%f }}, 
      {{ load_2:%f }}, 
      {{ load_3:%f }}
  - match: >
      CPU usage: 
      {{ cpu_usage_user:%p }} user, 
      {{ cpu_usage_sys:%p }} sys,
      {{ cpu_usage_idle:%p }} idle
  - match: >
      SharedLibs:
      {{ lib_resident:%mem }} resident,
      {{ lib_data:%mem }} data,
      {{ lib_linkedit:%mem }} linkedit.
  - match: >
      MemRegions:
      {{ mem_regions_total:%mem }} total,
      {{ mem_regions_resident:%mem }} resident,
      {{ mem_regions_private:%mem }} private,
      {{ mem_regions_shared:%mem }} shared.
  - match: >
      PhysMem:
      {{ phys_used:%mem }} used ({{ phys_wired:%mem }} wired),
      {{ phys_unused:%mem }} unused.
  - match: >
      VM:
      {{ vm_vsize:%mem }} vsize,
      {{ vm_frame_vsize:%mem }} framework vsize,
      {{ vm_swapins:(\d+\(\d+\)) }} swapins,
      {{ vm_swapouts:(\d+\(\d+\)) }} swapouts.
  - match: >
      Networks:
      packets: {{ net_packets_in:(\d+\/\d+[BKMG]?) }} in,
      {{ net_packets_out:(\d+\/\d+[BKMG]?) }} out.
  - match: >
      Disks:
      {{ disk_read:(\d+\/\d+[BKMG]?) }} read,
      {{ disk_written:(\d+\/\d+[BKMG]?) }} written.
  - repeat: 10
    match: >
      {{ pid:(\d+) }}
      {{ command:([\w\.\s]+) }}
      {{ pct_cpu:(\d+.\d+) }}
      {{ time:(\d{2}:\d{2}\.\d{2}) }}
      {{ num_th:([\d\/]+) }}
      {{ num_wq:%d }}
      {{ num_ports:(\d+)\+? }}
      {{ mem:%mem }}
      {{ purg:%mem }}
      {{ cmprs:%mem }}
      {{ pgrp:%d }}
      {{ ppid:%d }}
      {{ state:%w }}
      {{ boosts:(\*?\d+\+?\[\d+\+?\]) }}
      {{ cpu_me:%f }}
      {{ cpu_others:%f }}
      {{ uid:%d }}
      {{ faults:(\d+)\+? }}
      {{ cow:(\d+)\+? }}
      {{ msgsent:(\d+)\+? }}
      {{ msgrecv:(\d+)\+? }}
      {{ sysbsd:(\d+)\+? }}
      {{ sysmach:(\d+)\+? }}
      {{ csw:(\d+)\+? }}
      {{ pageins:(\d+)\+? }}
      {{ idlew:(\d+)\+? }}
      {{ power:(\d+.\d+) }}
      {{ user:%w }}
